### ISSUE TITLE
make bacnet write to 14 and 15 

### ISSUE THREAD

**Issue by NubeDev** [NubeDev/flow-eng#124]
### need to write null to 14 and 15 
after the values goes from a float to null we need to write `null` to 14 and or 15

https://github.com/NubeDev/flow-eng/blob/master/nodes/protocols/bacnet/mqtt.go#L78

to write at 14 and 15

to write `null`

```
json payload: {"value" : "null", "uuid" : ""}
```

```
topic := fmt.Sprintf("bacnet/%s/%d/write/pri/15", obj, objectId) // bacnet/ao/1/write/pv
```

### bacnet docs for mqtt
https://github.com/NubeIO/driver-bacnet#updating-bacnet-object-property-values-via-mqtt

**Comment by CanuckMarc** [comment]
closed with: https://github.com/NubeDev/flow-eng/pull/126
