### ISSUE TITLE
remove the logic to call FF points and schedule lists

### ISSUE THREAD

**Issue by NubeDev** [NubeDev/flow-eng#146]
remove the logic to call FF to get the latest points list and remove any code to MQTT subcribe to the points and schedules lists

as its been addded into the UI
https://github.com/NubeIO/rubix-ce/commit/ea04264d9d77c422a26b50c54c6b6ccd395932a2#diff-95b7955a516794c532f5245332a1fd4c9b8887676b645c95b54295b984b7b95fR487

**Comment by CanuckMarc** [comment]
https://github.com/NubeDev/flow-eng/tree/update/remove-ff-schedule-point-lists
