### ISSUE TITLE
Add `OnDeleted()` function

### ISSUE THREAD

**Issue by CanuckMarc** [NubeDev/flow-eng#50]
Some nodes need an `OnDeleted()` function that is called once the node is deleted.  

This is essential because any `go` functions (or other timers or services) that the node has started will need to be stopped.  This currently happens with MQTT subscriptions that are running in go routines on FF Network.

**Comment by CanuckMarc** [comment]
@RaiBnod I think this one is probably for you.  

The issue is like this: 

1. Node is added that has a timer (time.Ticker for example).
2. Flow is deployed, ticker starts.
3. Flow is edited and re-deployed.  At this point the ticker from the original node is still active.
4. Re-deployed node also starts a ticker.  

I think the root of the issue is that there is no function that takes care of disabling the go routines and timers that are running, when the flow is re-deployed.  Usually you would use a `defer` for this, but there is no function scope that works.

**Comment by RaiBnod** [comment]
We can find the example on the `Inject` node. Furthermore, this is another example:

[An_example_of_start_stop_lifecycle_call.patch](https://github.com/NubeDev/flow-eng/files/10323893/An_example_of_start_stop_lifecycle_call.patch)
